title: "Shanghai Workshop 2025"
description: "23rd China International Talent Exchange Conference - Data Science, Fintech and Digital Economy | October 20-23, 2025"
baseurl: "/2025-shanghai-workshop"
url: "https://digital-ai-finance.github.io"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

exclude:
  - download_images.py
  - "*.py"
  - README.md
  - nul
