title: "Shanghai Workshop 2025"
description: "23rd China International Talent Exchange Conference"
baseurl: "/2025-shanghai-workshop"
url: "https://digital-ai-finance.github.io"

markdown: kramdown
highlighter: rouge

exclude:
  - "*.py"
  - README.md
